name: scrap
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - requests
  - lxml
  - html5lib
  - json5
  - ipykernel
  - pip:
    - beautifulsoup4
    - requests-html
    - lxml_html_clean
    - tqdm
    - openpyxl
    - aiohttp
    - httpx
    - nest_asyncio
    - pandas
    - numpy